get_train_order = 'http://op.yikao666.cn/JDTrainOpen/getOrderForTN'
train_order_callback = 'http://op.yikao666.cn/JDTrainOpen/CallBackForTN?id=%s&success=%s'
save_order = 'http://localhost:8000/api/mobilepay/order'
set_order_status = 'http://localhost:8000/api/mobilepay/order/status/%s/%s'
get_account_tuniu = 'http://localhost:8000/api/mobilepay/account/tuniu'
put_account = 'http://localhost:8000/api/mobilepay/account/%d'
rsa_encode='http://115.28.102.142:8081/api/rsa/encode/%s'
